# Generated by Django 2.0.1 on 2021-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210925_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentity',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_heigth', null=True, upload_to='store', verbose_name='LOGO', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_heigth',
            field=models.IntegerField(null=True, verbose_name='LOGO高'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='LOGO宽'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
    ]
